// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flsklduipeqdzviwnlfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsc2tsZHVpcGVxZHp2aXdubGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzI5MTIsImV4cCI6MjA3NDIwODkxMn0.Qvu88IqatRTpLLfNqww8Ibou983AgjUidXCzT2rH9N0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});